#!/usr/bin/env Rscript

# Scores out-of-fold 48 h CIF predictions generated by 090 in a clean R session.

suppressPackageStartupMessages({
  library(cmprsk)
  library(data.table)
  library(prodlim)
  library(riskRegression)
  library(survival)
})

`%||%` <- function(x, y) {
  if (is.null(x)) y else x
}

script_arg <- grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE)
if (length(script_arg) != 1L) {
  stop("Run this file with Rscript so the project root can be resolved.")
}
script_path <- normalizePath(sub("^--file=", "", script_arg))
project_root <- normalizePath(file.path(dirname(script_path), ".."))

parse_args <- function(args) {
  out <- list()
  for (arg in args) {
    pair <- strsplit(sub("^--", "", arg), "=", fixed = TRUE)[[1]]
    if (!startsWith(arg, "--") || length(pair) != 2L) {
      stop("Arguments must use --name=value: ", arg)
    }
    out[[pair[1]]] <- pair[2]
  }
  out
}

args <- parse_args(commandArgs(trailingOnly = TRUE))
run_dir <- args$run_dir %||%
  file.path(project_root, "project_control/runs/20260827_finegray_baseline_v33")
horizon_hours <- as.numeric(args$horizon_hours %||% "48")
input_csv <- args$input %||%
  file.path(run_dir, "data/090_finegray_oof_predictions.csv")
if (!file.exists(input_csv)) {
  stop("OOF prediction file is missing: ", input_csv)
}

write_csv <- function(x, path) {
  data.table::fwrite(as.data.table(x), path, na = "")
}

observed_cif_at <- function(time, status, horizon) {
  estimate <- cmprsk::cuminc(ftime = time, fstatus = status, cencode = 0)
  cause_name <- grep("^1( |$)", names(estimate), value = TRUE)[1]
  if (is.na(cause_name)) {
    return(0)
  }
  curve <- estimate[[cause_name]]
  position <- findInterval(horizon, curve$time)
  if (position == 0L) 0 else as.numeric(curve$est[position])
}

# `riskRegression::Score` in the installed version rejects the data.frame
# subclass returned by fread for this competing-risk response. OOF files are
# small, so base R import avoids that package-interoperability issue.
oof <- utils::read.csv(input_csv, check.names = FALSE)
required_columns <- c("stay_id", "followup_hours_from_landmark", "fg_status_code")
missing_columns <- setdiff(required_columns, names(oof))
if (length(missing_columns) > 0L || anyDuplicated(oof$stay_id)) {
  stop("OOF prediction file is missing required columns or has duplicate stays.")
}
risk_columns <- grep(
  paste0("^cif", horizon_hours, "_"),
  names(oof),
  value = TRUE
)
if (length(risk_columns) == 0L) {
  stop("No OOF CIF columns found for the requested horizon.")
}

score_inputs <- lapply(risk_columns, function(column) as.numeric(oof[[column]]))
model_names <- sub(paste0("^cif", horizon_hours, "_"), "", risk_columns)
names(score_inputs) <- model_names
if (any(vapply(score_inputs, function(x) any(!is.finite(x) | x < 0 | x > 1), logical(1)))) {
  stop("At least one OOF CIF is non-finite or outside [0, 1].")
}

score_data <- data.frame(
  time = as.numeric(oof$followup_hours_from_landmark),
  status = as.integer(oof$fg_status_code)
)
score_object <- riskRegression::Score(
  object = score_inputs,
  formula = Hist(time, status) ~ 1,
  data = score_data,
  cause = 1,
  times = horizon_hours,
  metrics = c("auc", "brier"),
  plots = "calibration",
  summary = "risks",
  null.model = TRUE,
  conf.int = FALSE,
  se.fit = FALSE,
  verbose = 0
)

calibration_rows <- list()
for (model_name in model_names) {
  risk <- score_inputs[[model_name]]
  breaks <- unique(stats::quantile(risk, probs = seq(0, 1, by = 0.1), na.rm = TRUE))
  if (length(breaks) < 3L) {
    stop("Insufficient risk variation for calibration grouping: ", model_name)
  }
  groups <- cut(risk, breaks = breaks, include.lowest = TRUE, labels = FALSE)
  group_summary <- lapply(sort(unique(groups)), function(group) {
    rows <- groups == group
    data.frame(
      model = model_name,
      risk_group = group,
      n = sum(rows),
      mean_predicted_cif = mean(risk[rows]),
      observed_cif = observed_cif_at(
        oof$followup_hours_from_landmark[rows],
        oof$fg_status_code[rows],
        horizon_hours
      ),
      stringsAsFactors = FALSE
    )
  })
  calibration_rows[[model_name]] <- rbindlist(group_summary)
}

report_dir <- file.path(run_dir, "reports")
dir.create(report_dir, recursive = TRUE, showWarnings = FALSE)
write_csv(score_object$AUC$score, file.path(report_dir, "091_finegray_auc_48h.csv"))
write_csv(score_object$Brier$score, file.path(report_dir, "091_finegray_brier_48h.csv"))
write_csv(
  rbindlist(calibration_rows),
  file.path(report_dir, "091_finegray_calibration_deciles_48h.csv")
)
write_csv(
  score_object$Calibration$plotframe,
  file.path(report_dir, "091_finegray_calibration_plot_data_48h.csv")
)
writeLines(capture.output(sessionInfo()), file.path(report_dir, "091_sessionInfo.txt"))

message("Completed OOF Fine-Gray evaluation: ", run_dir)
